#!/bin/sh
# Cargar colores de wal
. "$HOME/.cache/wal/colors.sh"

dmenu_run \
    -c \
    -mw 600 \
    -l 10 \
    -bw 2 \
    -fn "JetBrains Mono:size=12" \
    -nb "$background" \
    -nf "$foreground" \
    -sb "$color1" \
    -sf "$foreground" \
    -p "  "
