#!/bin/sh

dev="/dev/ada1p3"
mnt="/mnt/linux"

if mount | grep -q "$mnt"; then
	doas umount "$mnt" && echo "Desmontado $mnt"
else
	kldstat | grep -q fusefs || doas kldload fusefs
	[ -d "$mnt" ] || doas mkdir -p "$mnt"
	doas fuse-ext2 "$dev" "$mnt" -o rw+ && echo "Montado $dev en $mnt"
fi
