#!/bin/sh

wall=$(find ~/pix/wall/ -type f \( -name "*.jpg" -o -name "*.png" \) | shuf -n 1)

# set wallpaper only on monitor 1
xwallpaper --output DP-0 --zoom "$wall"

# generate color scheme from monitor 1 wallpaper
wal -c
wal -n -s -t -e -i "$wall"

# aplicar colores a xrdb (dmenu los lee de aca)
xrdb -merge ~/.cache/wal/colors.Xresources
# aplicar colores a dwm
xrdb -merge ~/.cache/wal/colors-dwm.Xresources
killall -USR1 dwm
