#!/bin/sh

monitor1="DP-0"

wall=$(nsxiv -t -o "$HOME/pix/wall/" 2>/dev/null | head -1)
# -t = thumbnail mode, -o = print selected to stdout

[ -z "$wall" ] && exit 1

xwallpaper --output "$monitor1" --zoom "$wall"
wal -c
wal -n -i "$wall"

# aplicar colores a xrdb (dmenu los lee de aca)
xrdb -merge ~/.cache/wal/colors.Xresources
# aplicar colores a dwm
xrdb -merge ~/.cache/wal/colors-dwm.Xresources
killall -USR1 dwm
